export declare const CLIENT_DIR = "client";
export declare const BUILD_DIR = "build";
export declare const IS_PRODUCTION: boolean;
export declare const KUBERNETES_SERVICE_HOST: string;
export declare const KUBERNETES_SERVICE_PORT: number;
export declare const KUBERNETES_SERVICE_URL: string;
export declare const config: {
    IS_PRODUCTION: boolean;
    LENS_VERSION: string;
    LENS_THEME: string;
    BUILD_VERSION: string;
    API_PREFIX: {
        BASE: string;
        TENANT: string;
        TERMINAL: string;
        KUBE_BASE: string;
        KUBE_USERS: string;
        KUBE_HELM: string;
        KUBE_RESOURCE_APPLIER: string;
    };
    LOCAL_SERVER_PORT: number;
    WEBPACK_DEV_SERVER_PORT: number;
    SESSION_NAME: string;
    SESSION_SECRET: string;
    KUBE_CLUSTER_NAME: string;
    KUBE_CLUSTER_URL: string;
    KUBE_USERS_URL: string;
    KUBE_TERMINAL_URL: string;
    KUBE_HELM_URL: string;
    KUBE_RESOURCE_APPLIER_URL: string;
    KUBE_METRICS_URL: string;
    USER_MANAGEMENT_ENABLED: any;
    CHARTS_ENABLED: any;
    SERVICE_ACCOUNT_TOKEN: string;
    KUBERNETES_CA_CERT: string;
    KUBERNETES_CLIENT_CERT: string;
    KUBERNETES_CLIENT_KEY: string;
    KUBERNETES_TLS_SKIP: any;
    KUBERNETES_NAMESPACE: string;
};
export declare function isSecure(): boolean;
export default config;
export declare const clientVars: {
    BUILD_VERSION: string;
    IS_PRODUCTION: boolean;
    API_PREFIX: {
        BASE: string;
        TENANT: string;
        TERMINAL: string;
        KUBE_BASE: string;
        KUBE_USERS: string;
        KUBE_HELM: string;
        KUBE_RESOURCE_APPLIER: string;
    };
    TENANT_PREFIX: {
        BASE: string;
        TENANT: string;
        TERMINAL: string;
        KUBE_BASE: string;
        KUBE_USERS: string;
        KUBE_HELM: string;
        KUBE_RESOURCE_APPLIER: string;
    };
    LOCAL_SERVER_PORT: number;
};
export declare type IClientVars = typeof clientVars;
